config/routes.rb
Rails.application.routes.draw do

  resources :routes
  resources :cities
  resources :states
  resources :users
  resources :landmarks
  resources :waypoints

  post '/owner' => 'owners#create'
  patch '/owner' => 'owners#edit'
  delete '/owner' => 'owners#destroy'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  root 'main#index'

end

app/models/state.rb
class State < ActiveRecord::Base

	has_one :city, :dependent => :nullify
	has_many :cities, :dependent => :nullify

	has_many :landmarks, :through => :cities


end

app/controllers/states_controller.rb
class StatesController < ApplicationController

	def show
		@state = State.find_by(id: params[:id])
		@cities = @state.cities.order(population: :desc).paginate(:page => params[:page], :per_page => 10)
		
	end

	def index
		@states = State.paginate(:page => params[:page],:per_page => 10)
		if params[:keyword].present?
      		@states = @states.where("name LIKE ?", params[:keyword])
      		if !@states
      			flash["notice"] = "State not found"
      			redirect_to cities_path
      		end
      	end
   
	end
	
end

app/views/states/index.html.erb
<h2>States</h2>
<%= form_tag states_path, :method => :get do %>
<%= text_field_tag :keyword, '', placeholder: 'Search for a state' %>
<% end %>
<table>
<thead>
	<tr>
		<th>State Name</th>
		<th>Active Cities</th>
		<th>Active Landmarks</th>
	</tr>
</thead>

<tbody>

	<% @states.each do |state| %>
	<tr>
	<td> <%= link_to state.name, state_path(state)%></td>
	<td> <%= state.cities.count %> </td>
	<td><%= state.landmarks.count %></td>
	
	</tr>
	<% end %>
</tbody>
</table>
<br>
<%= will_paginate @states %>

app/views/states/show.html.erb
<h2><%= @state.name %> Information</h2>
<h4>Capital City: <%= @state.city.name %></h4>



<table class="city-table">
<thead>
	<tr>
		<th>City Name</th>
		<th>Population</th>
		<th>Landmarks</th>
	</tr>
</thead>

<tbody>

	<% @cities.each do |city| %>
	<tr>
	<td> <%= link_to city.name, city_path(city)%></td>
	<td> <%= number_with_delimiter(city.population, :delimiter => ',')  %></td>
	<td><%= city.landmarks.count %></td>
	</tr>
	<% end %>
</tbody>

<br>
<%= will_paginate @cities %>
</table>