config/routes.rb
Rails.application.routes.draw do

  resources :routes
  resources :cities
  resources :states
  resources :users
  resources :landmarks
  resources :waypoints

  post '/owner' => 'owners#create'
  patch '/owner' => 'owners#edit'
  delete '/owner' => 'owners#destroy'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  root 'main#index'

end

app/models/route.rb
class Route < ActiveRecord::Base
	
	has_many :waypoints
	has_many :owners
	has_many :users, :through => :owners
	has_many :cities, :through => :waypoints
	has_many :landmarks, :through => :cities
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

	def index
		@routes = Route.paginate(:page => params[:page],:per_page => 5)
		@cur_user = User.find_by(id: session[:user_id])
	end

	def show
		@route = Route.find_by(id: params[:id])
		@cur_user = User.find_by(id: session[:user_id])
	end

	def new
		@route = Route.new
	end

	def create
		route = Route.new
		route_params = params[:route]
		route.name = route_params[:name]
		route.legs = route_params[:legs]
		route.description = route_params[:description]
		route.save
		0.upto(route.legs) do |y|
			way = Waypoint.new
			way.route_id = route.id
			way.route_number = y
			way.save
		end
		
		flash["notice"] = route.name + " Created, now add waypoints!"
		redirect_to new_waypoint_path + '?route_id=' + route.id.to_s + '&leg=0'
		
	end
	def destroy
		route = Route.find_by(id: params[:id])
		if route
			flash["notice"] = route.name + " Deleted"
			route.destroy
		end
		
		redirect_to routes_path

	end
	def edit
		@route = Route.find_by(id: params[:id])
	end

	def update
		route = Route.find_by(id: params[:id])
		route_params = params[:route]
		route.name = route_params[:name]
		route.description = route_params[:description]
		route.legs = route_params[:legs]
		0.upto(route.legs) do |y|
			del = Waypoint.where(route_id: route.id, route_number: y)
			if del[0]
				del[0].delete
			end
			way = Waypoint.new
			way.route_id = route.id
			way.route_number = y
			way.save
		end
		
		route.save	
		flash["notice"] = route.name + " Updated, now add waypoints!"
		redirect_to new_waypoint_path + '?route_id=' + route.id.to_s + '&leg=0'

	end

end

app/views/routes/_add_links.html.erb
<% if cur_user %>
<% ur = Owner.where(user_id: cur_user.id, route_id: route.id)[0] %>

<% if !ur %>
<%= link_to "Add to my profile", owner_path + '?user_id=' + cur_user.id.to_s + '&route_id=' + route.id.to_s, method: :post %>
<% else %>

<% if ur.completed %>
<%= link_to "Mark as Undone", owner_path + '?user_id=' + cur_user.id.to_s + '&route_id=' + route.id.to_s + '&completed=0', method: :patch %>
<% else %>
<%= link_to "Mark as Completed", owner_path + '?user_id=' + cur_user.id.to_s + '&route_id=' + route.id.to_s + '&completed=1', method: :patch %>
<% end %>
<% end %>
<% end %>

app/views/routes/_form.html.erb
<%= form_for @route do |f| %>

  <p><%= f.label :name %><%= f.text_field :name, size: 40, autofocus: true, required: true %></p>
  <p><%= f.label :description %><%= f.text_area :description, size: "40x5" %></p>
  <p><%= f.label :legs %><%= f.text_field :legs, size: 40 %></p>
  <p><%= f.submit %></p>


  
<% end %>

app/views/routes/edit.html.erb
<h2>Change A Route</h2>
<%= render 'form' %>

app/views/routes/index.html.erb
<h1>Routes</h1>
<h4><%= link_to "Add a Route",new_route_path %></h4>
<% @routes.each do |route| %>
<ul>
	<li><%= link_to route.name, route_path(route) %></li>

<%= render 'add_links', :route => route, :cur_user => @cur_user %>

	<ol>
<% route.cities.order('route_number').each do |city| %>
<li><%= city.full_name %><% city.landmarks.each do |lm| %><%=' - ' + lm.name  %> 
<%end%>
</li>
<% end %>
</ol>

</ul>
<% end %>
<%= will_paginate @routes %>

app/views/routes/new.html.erb
<h2>Add A Route</h2>
<%= render 'form' %>

app/views/routes/show.html.erb
<h1><%= @route.name%></h1>
<p><%= @route.description %></p>
<h4>Cities</h4>
<ol>
<% ordered_cities = @route.cities.order('route_number') %>
<% ordered_cities.each do |city| %>
<li><%= link_to city.full_name, city_path(city)%></li>
<% end %>
</ol>

<h4>Map Your Route</h4>
<div id="map"></div>

<h2>Places You'll See</h2>



<% @route.landmarks.each do |lm| %>
<div class="side-block">
<%= image_tag lm.image_url, class: "landmark-thumbnail" %>
</div>
<%end%>
</div>

<% @route.landmarks.each do |lm| %>
<div class="side-block">
<p class="image-links"><%= link_to lm.name, landmark_path(lm)%></p> 
</div>
<% end %>
<div>
<p><%= link_to "Delete Route", route_path(@route), method: :delete %> <%= link_to "Edit Route", edit_route_path(@route)%>

<%= render 'add_links', :route => @route, :cur_user => @cur_user %>

<% lats = ordered_cities.map do |city| city.lat end %>
<% longs = ordered_cities.map do |city| city.long end %>
<% names = ordered_cities.map do |city| city.name end %>

<script>
 // Code edited from https://developers.google.com/maps/documentation/javascript/examples/directions-simple
  function initMap() {
  	var lats = <%= lats %>;
  	var longs = <%= longs%>;
  	var directionsService = new google.maps.DirectionsService;
  	var directionsDisplay = new google.maps.DirectionsRenderer;
    var mapDiv = document.getElementById('map');
    var map = new google.maps.Map(mapDiv, {
      center: {lat: 37.0902, lng: -95.7129},
      zoom: 3
    	}
    );
    directionsDisplay.setMap(map);
    
    calculateAndDisplayRoute(directionsService, directionsDisplay);
  	  

  }

function calculateAndDisplayRoute(directionsService, directionsDisplay) {
  var lats = <%= lats %>;
  var longs = <%= longs%>;
  var start = {lat: lats[0],lng: longs[0]};
  var end = {lat: lats[lats.length-1],lng: longs[longs.length-1]};
  var waypoints = [];
  for (var i = 1; i <= lats.length-2; i++) {
    	waypoints.push(
    		{location:{ lat: lats[i], lng: longs[i]}});
    	
		};
  	directionsService.route({
    origin: start,
    destination: end,
    waypoints: waypoints,
    travelMode: google.maps.TravelMode.DRIVING
  }, function(response, status) {
    if (status === google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    } else {
      window.alert('Directions request failed due to ' + status);
    }
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
    async defer></script>