config/routes.rb
Rails.application.routes.draw do

  resources :routes
  resources :cities
  resources :states
  resources :users
  resources :landmarks
  resources :waypoints

  post '/owner' => 'owners#create'
  patch '/owner' => 'owners#edit'
  delete '/owner' => 'owners#destroy'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  root 'main#index'

end

app/models/city.rb
class City < ActiveRecord::Base

	belongs_to :state 
	has_many :landmarks
	has_many :waypoints
	has_many :routes, :through => :waypoints
	validates :state_id, presence: true
	validates :name, presence: true
	
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

	def show
		@city = City.find_by(id: params[:id])
		
	end

	def index
		@cities = City.order(:name).paginate(:page => params[:page],:per_page => 50)
		if params[:keyword].present?
      		@cities = @cities.where("full_name LIKE ? OR name = ?", "%#{params[:keyword]}%", params[:keyword])
      		if !@cities
      			flash["notice"] = "City not found"
      			redirect_to cities_path
      		end
    	end

	end

	def new
		@city = City.new
	end

	def create
		city_params = params[:city]
		city = City.new
		city.name = city_params[:name]
		city.state_id = city_params[:state_id]
		city.lat = city_params[:lat]
		city.long = city_params[:long]
		city.population = city_params[:population]
		state = State.find_by(id: city_params[:state_id])
		city.full_name = city.name + ', ' + state.abbreviation
		city.save
		flash["notice"] = city_params[:name] + " Added!"
		redirect_to cities_path
	end

	def edit
		@city = City.find_by(id: params[:id])
	end

	def update
		city = City.find_by(id: params[:id])
		city_params = params[:city]
		city.name = city_params[:name]
		city.state_id = city_params[:state_id]
		city.lat = city_params[:lat]
		city.long = city_params[:long]
		city.population = city_params[:population]
		state = State.find_by(id: city_params[:state_id])
		city.full_name = city.name + ', ' + state.abbreviation
		city.save
		flash["notice"] = city_params[:name] + " Edited!"
		redirect_to city_path(city)
	end
	def destroy
		city = City.find_by(id: params[:id])
		if city
			flash["notice"] = city.full_name + " Deleted"
			city.destroy
		end
		
		redirect_to cities_path
	end

	
end

app/views/cities/_form.html.erb
<%= link_to "Add a Landmark", new_landmark_path %>
<%= form_for @city do |f| %>

  <p><%= f.label :name %><%= f.text_field :name, size: 40, autofocus: true, required: true %></p>
  <p><%= f.label :population %><%= f.text_field :population, size: 40%></p>
  <p>Lat/Long are optional but are required for city to appear on map</p>
  <p><%= f.label :lat %><%= f.text_field :lat, size: 40 %></p>
  <p><%= f.label :long %><%= f.text_field :long, size: 40%></p>
  <p><%= f.collection_select :state_id, State.all.order('name'), :id, :name %></p>
  

  <p><%= f.submit %></p>


  
<% end %>

app/views/cities/edit.html.erb
<h2>Edit A City</h2>
<%= render 'form' %>

app/views/cities/index.html.erb
<h1>Cities</h1>

<h5><%= link_to "Add a City", new_city_path %></h5>
<%= form_tag cities_path, :method => :get do %>
<%= text_field_tag :keyword, '', placeholder: 'Search for a city' %>
<% end %>

<table>
<thead>
	<tr>
		<th>City Name</th>
		<th>Population</th>
		<th>Active Landmarks</th>
		<th>Delete City</th>
	</tr>
</thead>

<tbody>

	<% @cities.each do |city| %>
	<tr>
	<td> <%= link_to city.full_name, city_path(city)%></td>
	<% if city.population %>
	<td><%= number_with_delimiter(city.population, :delimiter =>',')%></td>
	<% else %>
	<td>&lt37,000</td>
	<% end %>
	
	<td><%= city.landmarks.count %></td>
	<td><%= link_to "Delete City", city_path(city), method: :delete%></td>
	
	</tr>
	<% end %>
</tbody>
</table>
<br>
<%= will_paginate @cities %>

app/views/cities/new.html.erb
<h2>Add A City</h2>
<%= render 'form' %>

app/views/cities/show.html.erb
<h2>About <%= @city.name + ', ' + @city.state.name %></h2>
<br>
<h3>Population <%= number_with_delimiter(@city.population, :delimiter =>',') %></h3>
<br>

<h3>Nearby Landmarks:</h3>
<% if @city.landmarks.length == 0 %>
<p>No Landmarks</p>
<% else %>
<ul>
<% @city.landmarks.each do |landmark| %>
<li><%= link_to landmark.name,landmark_path(landmark) %> </li>
<% end %>
<% end %>
<%= link_to "Add a Landmark", new_landmark_path %>
</ul>
<h4>Routes that visits <%= @city.name %></h4>
<ul>
<% @city.routes.to_set.each do |route| %>
<li><%= link_to route.name, route_path(route)%></li>
<%end%>
</ul>
<%= link_to "Edit City", edit_city_path(@city)%>
<%= link_to "Delete City", city_path(@city), method: :delete%>